<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>ff155ed9-b427-4d66-9e08-7bc6fd1c3ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.mt-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
