<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Dashboard</name>
   <tag></tag>
   <elementGuidId>45da954e-b969-41e9-a499-9d8ea190c19d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.text-lg</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
